; this block defines names for joypad
; direction and button bits

JOY_I		= $01
JOY_II		= $02
JOY_SEL		= $04
JOY_RUN		= $08
JOY_UP		= $10
JOY_RIGHT	= $20
JOY_DOWN	= $40
JOY_LEFT	= $80

JOY_TYPE6	= $50
JOY_III		= $01
JOY_IV		= $02
JOY_V		= $04
JOY_VI		= $08

JOY_BITI	= $0
JOY_BITII	= $1
JOY_BITSEL	= $2
JOY_BITRUN	= $3
JOY_BITUP	= $4
JOY_BITRT	= $5
JOY_BITDN	= $6
JOY_BITLT	= $7

JOY_BITIII	= $0
JOY_BITIV	= $1
JOY_BITV	= $2
JOY_BITVI	= $3
